id:
  _var: id
type: Box
layout:
  span: 24
blocks:
  - id: physics_tree
    type: EChart
    properties:
      option:
        tooltip:
          trigger: item
          triggerOn: mousemove
        series:
          - type: tree
            data:
              - _ref:
                  path: test_tree.yaml
                  vars:
                    field:
                      _var: field
            top: 10%
            left: 20%
            bottom: 10%
            right: 20%
            symbolSize: 10
            label:
              position: left
              verticalAlign: middle
              align: right
              fontSize: 14
            leaves:
              label:
                position: right
                verticalAlign: middle
                align: left
            emphasis:
              focus: descendant
            expandAndCollapse: true
            animationDuration: 550
            animationDurationUpdate: 750
      height: 500